
---
- name: Install Services on WebServers
  hosts: web_servers

  tasks:
   - name: update
     apt: update_cache=yes

   - name: Install Apache2, Proftpd, Snmpd, Postifx, Vim and PHP7.
     apt: name={{item}} state=present
     with_items:
          - apache2
          - proftpd
          - snmpd
          - postfix
          - vim
          - php7.0

   - name: Copy Application Data to WebServers
     copy:
       src: /Users/jeansullivan/Documents/devopinhos/git-projects/jean-ansible/code/
       dest: /var/www/html/

   - name: Download App Wordpress on WebServers
     script: script.sh

   - name: restart all services
     service: name={{item}} state=restarted
     with_items:
          - apache2
          - proftpd
          - snmpd
          - postfix
